In [88]:
# ! pip install numpy

#  Numpy 
NumPy (Numerical Python) एक open-source Python library है जो multi-dimensional arrays और high-speed mathematical operations प्रदान करती है। यह Data Science, Machine Learning, AI और Scientific Computing में व्यापक रूप से उपयोग की जाती है।

NumPy की Features
### 1. Fast Processing

NumPy का core C language में लिखा गया है, इसलिए Python lists से काफी तेज चलता है।

### 2. Less Memory Usage

NumPy arrays Python lists की तुलना में कम memory लेते हैं।

### 3. Multi-Dimensional Arrays
* 1D Array
* 2D Array
* 3D Array
* N-Dimensional Array

### 4. Mathematical Functions
* Addition
* Subtraction
* Multiplication
* Division
* Power
* Square Root
* Logarithm

### 5. Linear Algebra
* Matrix multiplication
* Determinant
* Inverse
* Eigen values

** ## Array Attributes **<br>


arr.ndim      # Dimensions<br>
arr.shape     # Shape<br>
arr.size      # Total elements<br>
arr.dtype     # Data type<br>
arr.itemsize  # Size of one element<br>
arr.nbytes    # Total memory<br>



In [89]:
# pip install numpy
print("hello hii kese ho ")

hello hii kese ho 


In [90]:

# python -m venv 
# venv/Scripts/activate
# deactivate
import numpy as np 

In [91]:
np.__version__

'2.4.6'

In [92]:
lst =list(range(1,20))

In [93]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [94]:
type(lst)

list

In [95]:

arr =np.array(lst)

In [96]:
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [97]:

lst = [1,2,5,2,5,5]
arr =np.array(lst)

In [98]:
type(arr) 

numpy.ndarray

In [99]:
arr =np.array([1,2,5,2,58,2,8,2,5,522,5,2,5,2,5,2,5,5])

In [100]:

arr =np.array([range(1,20)])

In [101]:
type(arr )

numpy.ndarray

In [102]:
arr =np.arange(1,21)

In [103]:
type(arr)

numpy.ndarray

In [104]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [105]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [106]:
arr =np.ones(10)

In [107]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [108]:
arr =np.zeros((5,10)) 
arr


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [109]:
arr =np.zeros((5,10)) 
print(arr.ndim)


2


In [110]:
arr =np.linspace(1,10,5)
print(arr)
print(type(arr ))

[ 1.    3.25  5.5   7.75 10.  ]
<class 'numpy.ndarray'>


In [111]:
arr =np.linspace(1,10,5)
print(arr)
print(type(arr ))

[ 1.    3.25  5.5   7.75 10.  ]
<class 'numpy.ndarray'>


In [112]:
arr 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [113]:
arr =np.arange(0,30)

In [114]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [115]:
# np.reshape()
arr =arr.reshape(10,3)


In [116]:
arr 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [117]:

arr =arr.reshape(5,6)

In [118]:
arr 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [119]:

arr =arr.reshape(6,5)

In [120]:
arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [121]:
arr = np.random.randint(1,5,10)
arr 

array([4, 2, 1, 3, 2, 3, 4, 4, 3, 2], dtype=int32)

In [122]:
arr = np.random.randint(1,5,(5,6))
arr 

array([[2, 1, 1, 2, 3, 1],
       [1, 1, 4, 3, 4, 4],
       [2, 2, 3, 3, 3, 3],
       [3, 1, 4, 3, 4, 1],
       [4, 2, 2, 4, 4, 4]], dtype=int32)

In [123]:
arr =np.random.random(10)
arr 

array([0.6520232 , 0.42622913, 0.03405125, 0.81228991, 0.59436229,
       0.0052499 , 0.41775221, 0.77953388, 0.63388658, 0.73632004])

In [124]:
arr =np.random.random((10, 3))
arr 

array([[0.69213541, 0.14285771, 0.25717251],
       [0.74594706, 0.95470291, 0.19328423],
       [0.20350374, 0.88588607, 0.41149407],
       [0.17601347, 0.96239902, 0.70544739],
       [0.46322184, 0.08253387, 0.02715553],
       [0.9793546 , 0.17326266, 0.71315395],
       [0.23226841, 0.74121669, 0.91354505],
       [0.35235008, 0.89027578, 0.61970915],
       [0.30370359, 0.02798131, 0.43234199],
       [0.16277593, 0.70571762, 0.31548261]])

In [125]:
arr =np.arange(60).reshape(12,5)
arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [126]:
print("number of dim :- ",arr.ndim)
print("shape of array :- ",arr.shape)
print("data types of item:- ",arr.dtype)
print("size of array :- ",arr.size)

number of dim :-  2
shape of array :-  (12, 5)
data types of item:-  int64
size of array :-  60


In [127]:
lst = [[1,2,3],[4,5,6]]
lst 

[[1, 2, 3], [4, 5, 6]]

In [128]:
arr =np.array(lst)

In [129]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
arr =np.arange(60).reshape(12,5)

In [131]:
arr.shape

(12, 5)

In [132]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [133]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [134]:
arr.transpose

<function ndarray.transpose(*axes)>

In [137]:
arr[0][0]

np.int64(0)

In [138]:

arr[11,4]

np.int64(59)

In [139]:
arr[-1,-1]

np.int64(59)

In [140]:
arr[11,-1]

np.int64(59)

In [141]:
arr[-1,4]

np.int64(59)

In [142]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [143]:
arr[0:9,3:4]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28],
       [33],
       [38],
       [43]])

In [144]:
arr[2:4,3:]

array([[13, 14],
       [18, 19]])

In [145]:
arr[9:11,1:3]

array([[46, 47],
       [51, 52]])

In [146]:
arr[5:7,2:4]

array([[27, 28],
       [32, 33]])

In [147]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [148]:
arr[-1,-1]=100

In [149]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58, 100]])

In [150]:

print("number of dim :- ",arr.ndim)
print("shape of array :- ",arr.shape)
print("data types of item:- ",arr.dtype)
print("size of array :- ",arr.size)

number of dim :-  2
shape of array :-  (12, 5)
data types of item:-  int64
size of array :-  60


In [153]:
arr =np.arange(225).reshape(5,15,3)

In [154]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [155]:
arr[0][0][0]

np.int64(0)

In [156]:
arr[-1]

array([[180, 181, 182],
       [183, 184, 185],
       [186, 187, 188],
       [189, 190, 191],
       [192, 193, 194],
       [195, 196, 197],
       [198, 199, 200],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [210, 211, 212],
       [213, 214, 215],
       [216, 217, 218],
       [219, 220, 221],
       [222, 223, 224]])

In [157]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [158]:
arr[0,0,0]

np.int64(0)

In [159]:
arr[0:5,0]


array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [160]:
arr[0,0,0]

np.int64(0)

In [161]:
arr[0:5,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [162]:
print("number of dim :- ",arr.ndim)
print("shape of array :- ",arr.shape)
print("data types of item:- ",arr.dtype)
print("size of array :- ",arr.size)

number of dim :-  3
shape of array :-  (5, 15, 3)
data types of item:-  int64
size of array :-  225


In [163]:
arr1 = np.array([1,2,89,2,8,2,8])
arr2 =np.array([8,5,2,6,25,2,52])
print(arr1*arr2)
print(arr1/arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*+arr2)
print(arr1//+arr2)

[  8  10 178  12 200   4 416]
[ 0.125       0.4        44.5         0.33333333  0.32        1.
  0.15384615]
[ 9  7 91  8 33  4 60]
[ -7  -3  87  -4 -17   0 -44]
[  8  10 178  12 200   4 416]
[ 0  0 44  0  0  1  0]


In [164]:
# ==============================
# NumPy Array Operations Example
# ==============================

import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)

print("\n========== OPERATIONS ==========\n")

# Multiplication
print("1️⃣ Multiplication (*)")
print("arr1 * arr2 =", arr1 * arr2)

# Division
print("\n2️⃣ Division (/)")
print("arr1 / arr2 =", arr1 / arr2)

# Addition
print("\n3️⃣ Addition (+)")
print("arr1 + arr2 =", arr1 + arr2)

# Subtraction
print("\n4️⃣ Subtraction (-)")
print("arr1 - arr2 =", arr1 - arr2)

# Positive Sign with Multiplication
print("\n5️⃣ Multiplication with Unary Plus (* +)")
print("arr1 * +arr2 =", arr1 * +arr2)

# Floor Division
print("\n6️⃣ Floor Division (//)")
print("arr1 // +arr2 =", arr1 // +arr2)

print("\n✅ All operations completed successfully!")

Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]

========== OPERATIONS ==========

1️⃣ Multiplication (*)
arr1 * arr2 = [ 20  80 180 320]

2️⃣ Division (/)
arr1 / arr2 = [5. 5. 5. 5.]

3️⃣ Addition (+)
arr1 + arr2 = [12 24 36 48]

4️⃣ Subtraction (-)
arr1 - arr2 = [ 8 16 24 32]

5️⃣ Multiplication with Unary Plus (* +)
arr1 * +arr2 = [ 20  80 180 320]

6️⃣ Floor Division (//)
arr1 // +arr2 = [5 5 5 5]

✅ All operations completed successfully!


In [165]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)

Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]


In [166]:
arr1.sort()

In [167]:
arr =np.arange(225)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [168]:
arr =arr.reshape(5,15,3)

In [169]:
arr


array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11